### ISSUE TITLE
Error on plugin loading

### ISSUE THREAD

**Issue by highend** [guillermooo/Vintageous_Plugin_Surround#1]
Hi,

ST3 Build 3047 Portable
Windows 7 SP1 x64 German

I get this right after starting up ST3:

```
reloading plugin Vintageous.actions
reloading plugin Vintageous.ex_commands
reloading plugin Vintageous.ex_main
reloading plugin Vintageous.ex_motions
reloading plugin Vintageous.jump_list_cmds
reloading plugin Vintageous.motions
reloading plugin Vintageous.run
reloading plugin Vintageous.state
reloading plugin Vintageous.test_runner
reloading plugin Vintageous.transformers
reloading plugin Vintageous.transformers_visual
reloading plugin Vintageous_Plugin_Surround.action_cmds
reloading plugin Vintageous_Plugin_Surround.builder
Traceback (most recent call last):
  File "D:\Tools\Sublime Text\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "D:\Tools\Sublime Text\Data\Packages\Vintageous_Plugin_Surround\builder.py", line 16, in <module>
    description="Builds .sublime-package archives.")
  File "X/argparse.py", line 1598, in __init__
AttributeError: 'module' object has no attribute 'argv'
plugins loaded
```

**Comment by guillermooo** [comment]
It looks like you're using the repo checkout rather than the _.sublime-package_ file? The error looks harmless, though.

**Comment by highend** [comment]
```
It looks like you're using the repo checkout rather than the .sublime-package file?
```

Yes, that's correct.

```
The error looks harmless, though.
```

Ok, just wanted to report it. :)
