### ISSUE TITLE
OSX, recent change to Vintageous, no longer working

### ISSUE THREAD

**Issue by edubkendo** [guillermooo/Vintageous_Plugin_Surround#5]
After a recent update to Vintageous, this stopped working for me. During startup, the following was output to the console:

```

reloading plugin Vintageous_Plugin_Surround.action_cmds
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "action_cmds in /Users/ericwest/Library/Application Support/Sublime Text 3/Installed Packages/Vintageous_Plugin_Surround.sublime-package", line 4, in <module>
ImportError: cannot import name regions_transformer

```

**Comment by guillermooo** [comment]
Yeah, this plugin is unfortunately not supported now. There's some work left to be done before it can be re-enabled.

**Comment by eelkeh** [comment]
Any updates on this issue? It would be great to use it again.

**Comment by guillermooo** [comment]
The plugin should be working normally now. I'm using it, but please report any problems.

**Comment by eelkeh** [comment]
It works now after building from the repository, the bitbucket release didn't work for me.
