### ISSUE TITLE
Some errors on loading in ST3, build 3062

### ISSUE THREAD

**Issue by taasaa** [guillermooo/Vintageous_Plugin_Surround#8]
The functionality is still there, but here's backtrace from the ST's console.

Unfortunately i'm not a python guy, so no idea how to dig deeper, sorry.

```
reloading plugin Vintageous_Plugin_Surround.action_cmds
reloading plugin Vintageous_Plugin_Surround.builder
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/michael/Library/Application Support/Sublime Text 3/Packages/Vintageous_Plugin_Surround/builder.py", line 16, in <module>
    description="Builds .sublime-package archives.")
  File "./argparse.py", line 1598, in __init__
AttributeError: 'module' object has no attribute 'argv'
reloading plugin Vintageous_Plugin_Surround.test_runner
```

**Comment by taasaa** [comment]
Thanks for the plugin btw, should've started with that :)

**Comment by aminfara** [comment]
+1
I get the same error. Googled it and the following might be the reason.
http://stackoverflow.com/questions/6605851/python-newbie-working-with-argparse
